In [15]:
import pandas as pd
df = pd.read_csv(r"D:\study_marks.csv")
df

Study_Hours  Marks
0          2.9   27.0
1          5.8   61.0
2          4.7   45.0
3          4.0   38.0
4          1.8   19.0
5          1.8    8.0
6          1.3    4.0
7          5.3   50.0
8          4.0   35.0
9          4.5   47.0

In [17]:
df['Marks'].max()

61.0

In [19]:
df['Marks'].min()

4.0

In [21]:
df['Marks'].describe()

count    10.000000
mean     33.400000
std      18.673808
min       4.000000
25%      21.000000
50%      36.500000
75%      46.500000
max      61.000000
Name: Marks, dtype: float64

In [23]:
df[df.Marks == df.Marks.max()]

Study_Hours  Marks
1          5.8   61.0

In [25]:
df[df.Marks == df.Marks.min()]

Study_Hours  Marks
6          1.3    4.0

In [27]:
df.count()

Study_Hours    10
Marks          10
dtype: int64

In [29]:
df['Marks'].nunique()

10

In [31]:
df.cov()

Study_Hours       Marks
Study_Hours     2.481000   28.906667
Marks          28.906667  348.711111

In [33]:
df.corr()

Study_Hours    Marks
Study_Hours      1.00000  0.98277
Marks            0.98277  1.00000

In [35]:
df.std()

Study_Hours     1.575119
Marks          18.673808
dtype: float64

In [37]:
df.var()

Study_Hours      2.481000
Marks          348.711111
dtype: float64

# Normalization

In [40]:
s=pd.Series([1000,2000,3000,4000])
s

0    1000
1    2000
2    3000
3    4000
dtype: int64

In [42]:
v=((1000-1000)/(4000-1000))
v

0.0

In [44]:
v=((2000-1000)/(4000-1000))            #v=(x-min()/max()-min())
v

0.3333333333333333

In [46]:
v=((3000-1000)/(4000-1000))
v

0.6666666666666666

In [48]:
v=((4000-1000)/(4000-1000))
v

1.0

In [50]:
s.min()

1000

In [52]:
s.max()

4000

In [54]:
sd=(s-s.min())/(s.max()-s.min())
sd

0    0.000000
1    0.333333
2    0.666667
3    1.000000
dtype: float64

In [56]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler

In [58]:
import pandas as pd

In [60]:
sd=MinMaxScaler().fit_transform(s.values.reshape(-1,1))
sd

array([[0.        ],
       [0.33333333],
       [0.66666667],
       [1.        ]])

In [62]:
data={
    "temp":[-20,-30,-40,-60],
    "hum":[100,150,140,130]
}
df=pd.DataFrame(data)
df

temp  hum
0   -20  100
1   -30  150
2   -40  140
3   -60  130

In [64]:
norm_data=MinMaxScaler().fit_transform(df)    ####normalization
norm_data

array([[1.  , 0.  ],
       [0.75, 1.  ],
       [0.5 , 0.8 ],
       [0.  , 0.6 ]])

In [66]:
norm_df=pd.DataFrame(norm_data,columns=df.columns)
norm_df

temp  hum
0  1.00  0.0
1  0.75  1.0
2  0.50  0.8
3  0.00  0.6

# Standardization

In [69]:
s=pd.Series([1000,2000,3000,4000])
s

0    1000
1    2000
2    3000
3    4000
dtype: int64

In [71]:
s.mean()

2500.0

In [73]:
s.std()

1290.9944487358057

In [75]:
zscore=(s-s.mean())/s.std()
zscore

0   -1.161895
1   -0.387298
2    0.387298
3    1.161895
dtype: float64

In [77]:
zscore=StandardScaler().fit_transform(s.values.reshape(-1,1))
zscore

array([[-1.34164079],
       [-0.4472136 ],
       [ 0.4472136 ],
       [ 1.34164079]])

In [79]:
zscore=(s-s.mean())/s.std(ddof=0)
zscore

0   -1.341641
1   -0.447214
2    0.447214
3    1.341641
dtype: float64

In [81]:
data={
    "temp":[-20,-30,-40,-60],
    "hum":[100,150,140,130]
}
df=pd.DataFrame(data)
df

temp  hum
0   -20  100
1   -30  150
2   -40  140
3   -60  130

In [83]:
zscore=StandardScaler().fit_transform(df)
zscoredf=pd.DataFrame(zscore, columns=df.columns)
zscore

array([[ 1.18321596, -1.60356745],
       [ 0.50709255,  1.06904497],
       [-0.16903085,  0.53452248],
       [-1.52127766,  0.        ]])

In [85]:
zscoredf

temp       hum
0  1.183216 -1.603567
1  0.507093  1.069045
2 -0.169031  0.534522
3 -1.521278  0.000000